apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplikasi-nginx
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: aplikasi-nginx
  template:
    metadata:
      labels:
        app: aplikasi-nginx
    spec:
      containers:
      - name: aplikasi-nginx
        image: nginx:latest
        resources:
          limits:
            memory: "10Mi"
            cpu: "10m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  #type: CLusterIP
  selector:
    app: aplikasi-nginx
  ports:
  - port: 8080
    targetPort: 80
